//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pp
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public int classid { get; set; }
        public string classname { get; set; }
        public Nullable<int> subjectid { get; set; }
    
        public virtual subject subject { get; set; }
    }
}
